name: Train and Convert Model

on: [push]  # Runs every time you push code

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub's Linux VM
    
    steps:
    - uses: actions/checkout@v4  # Check out your repo code
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install tensorflow==2.12.0
        pip install tensorflowjs==4.4.0
        pip install numpy==1.24.3
        
    - name: Train and convert model
      run: |
        python train_cifar10.py
        tensorflowjs_converter \
          --input_format=keras \
          --output_format=tfjs_layers_model \
          --quantization_bytes=2 \
          ./cifar10_model.h5 \
          ./tfjs_model
        
    - name: Upload model
      uses: actions/upload-artifact@v3
      with:
        name: tfjs-model
        path: tfjs_model/
